title: ALL POSTS ğŸ“–
description: know it then do itğŸ¬
author: QQ love member No. 3 seed player
github: https://github.com/ppbibo
about: know it then do it && APT086&QQæ„›å®‰å…¨å®éªŒå®¤æˆå‘˜
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/ppbibo"
      

urls:
    - text: Tags ğŸ·ï¸
      url: /category/security
    - text: About Me ğŸ‘ˆ
      url: /about/
    - text: Links ğŸ”—
      url: /links/
    - text: é™ˆå©·å©· ğŸ’—
      url: /chentingting/
    - text: APT086 &QQæ„›å®‰å…¨å®éªŒå®¤ğŸ‘
      url: https://ctf.dog/qqlovelab/
    - text: XML Feed ğŸ§¾
      url: /feed.xml

url: "https://6o9.im"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
